// Code generated by "stringer -type=PlayType"; DO NOT EDIT.

package game

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Single-0]
	_ = x[Double-1]
	_ = x[Triple-2]
	_ = x[HomeRun-3]
	_ = x[CaughtStealing-4]
	_ = x[HitByPitch-5]
	_ = x[Walk-6]
	_ = x[StolenBase-7]
	_ = x[PickedOff-8]
	_ = x[CatcherInterference-9]
	_ = x[ReachedOnError-10]
	_ = x[FieldersChoice-11]
	_ = x[WildPitch-12]
	_ = x[PassedBall-13]
	_ = x[GroundOut-14]
	_ = x[FlyOut-15]
	_ = x[DoublePlay-16]
	_ = x[TriplePlay-17]
	_ = x[StrikeOut-18]
	_ = x[StrikeOutPassedBall-19]
	_ = x[StrikeOutWildPitch-20]
	_ = x[FoulFlyError-21]
	_ = x[NoPlay-22]
}

const _PlayType_name = "SingleDoubleTripleHomeRunCaughtStealingHitByPitchWalkStolenBasePickedOffCatcherInterferenceReachedOnErrorFieldersChoiceWildPitchPassedBallGroundOutFlyOutDoublePlayTriplePlayStrikeOutStrikeOutPassedBallStrikeOutWildPitchFoulFlyErrorNoPlay"

var _PlayType_index = [...]uint8{0, 6, 12, 18, 25, 39, 49, 53, 63, 72, 91, 105, 119, 128, 138, 147, 153, 163, 173, 182, 201, 219, 231, 237}

func (i PlayType) String() string {
	if i >= PlayType(len(_PlayType_index)-1) {
		return "PlayType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PlayType_name[_PlayType_index[i]:_PlayType_index[i+1]]
}
